### ISSUE TITLE
Update licence

### ISSUE THREAD

**Issue by dmey** [WRF-CMake/wrf#15]
To be consistent with other repos/projects, we should modify the licence text to:
```
# WRF-CMake (https://github.com/WRF-CMake/WRF).
# Copyright 2018-2019 M. Riechert and D. Meyer. Licensed under the MIT License.
```

**Comment by letmaik** [comment]
I think we should only include the beginning year of the copyright, as we have it currently. Otherwise you have to constantly update this header. Did you see evidence that it's common practice to include a year span? Some projects have "2018-present", but honestly, I don't think it makes any difference copyright law-wise. The most correct way would probably to treat each file individually and the year then says when the file was first created, so there could be a mix of 2018 and 2019. But again, I think it's overkill. Microsoft for example doesn't include any year in file headers.

**Comment by dmey** [comment]
This can just be a copy and replace but, yes, I am fine with just keeping the date the file was first created or modified -- my understanding is that the copyright year should be modified when you make changes to it.

**Comment by letmaik** [comment]
I think the point of the copyright is to say "I came up with this intellectual property in 2018", so you don't really want to change the first year. It gets blurry, esp. when changing files, but fortunately our work is mostly an addon of new files.

**Comment by dmey** [comment]
What I meant is to simply append the year to the copyright header when you make changes to a file. For example 2018-2019 as shown in my original post. Or 2018, 2020 if you do not have consecutive years.

**Comment by letmaik** [comment]
I had a look at this [again](https://softwareengineering.stackexchange.com/a/124692). To avoid maintenance/cognitive overhead I'll only put the year a file was created/first modified in our copyright header. The License file itself will have the first year overall.

**Comment by dmey** [comment]
Agree.
