### ISSUE TITLE
Minor issue: cononicalize install locations on macOS (and Linux?)

### ISSUE THREAD

**Issue by zbeekman** [WRF-CMake/wrf#27]
I haven't tried `make install` on linux yet, but on macOS it puts executables into an abnormal directory structure: `<prefix>/{main,test}`.

Also, `.exe` suffix is not commonly used outside of windows. CMake should handle that automatically for you.

As for the directory structure, I would recommend using [`GNUInstallDirs`](https://cmake.org/cmake/help/v3.1/module/GNUInstallDirs.html) on macOS and Linux and putting binaries into `${CMAKE_INSTALL_BINDIR}` and the test/examples directory can be installed into `${CMAKE_INSTALL_DATADIR}/wrf`.

**Comment by letmaik** [comment]
All great suggestions, and of course we would never come up ourselves with such a weird structure and executable extensions on non-Windows. Welcome to the world of WRF :) We need to keep these exact folders and filenames to match what the existing build system does, so that users can keep their work flows and follow the original documentation and use WRF-CMake as a drop-in. Sorry :/
